### ISSUE TITLE
Novatos perdidos

### ISSUE THREAD

**Issue by aiedonline** [esbjs/nodejsdev#2]
O projeto precisa de um PDF ensinando a instalar o ambiente, completo des do inicio.

**Comment by GabrielKiesshau** [comment]
O manual foi feito meses atras, segue o link do mesmo: https://docs.google.com/document/d/1KPk5cAkS4pVQ4hNpHIsS4dvPh9XxtleHCMqTbWrcDVA/edit?usp=drivesdk
